---
title: "Chapter 12"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
```

# 12.2 Tidy data
```{r}
table1
table2
table3
table4a
table4b

# rate per 10,000
table1 %>%
  mutate(rate = cases / population * 10000)

# Cases per year
table1 %>%
  count(year, wt = cases)

# Visualize changes over time
ggplot(table1, aes(year, cases)) +
  geom_line(aes(group = country), color = "grey50") +
  geom_point(aes(color = country))
```

# 12.2.1 Exercises
```{r}
# 3
(table2 %>%
   filter(type == "cases") %>%
   ggplot(aes(year, count)) +
    geom_line(aes(group = country), color = "grey50") +
    geom_point(aes(color = country)))
```

# 12.3.1 Gathering
```{r}
table4a

# Both of these do the same thing
(table4a %>%
    gather(`1999`, `2000`, key = "year", value = "cases"))

(table4a %>%
    gather(2:3, key = "year", value = "cases"))

table4b

(table4b %>%
    gather(2:3, key = "year", value = "population"))

# Tidy up table4a and table4b into one table
tidy4a <- table4a %>%
  gather(2:3, key = "year", value = "cases")
tidy4b <- table4b %>%
  gather(2:3, key = "year", value = "population")
(left_join(tidy4a, tidy4b))
```

# 12.3.2 Spreading
```{r}
table2 %>%
  spread(key = type, value = count)
```

# 12.3.3 Exercises
```{r}
# 1
(stocks <- tibble(
  year = c(2015, 2015, 2016, 2016),
  half = c(1, 2, 1, 2),
  return = c(1.88, 0.59, 0.92, 0.178)
))

(spr <- stocks %>%
    spread(key = year, value = return))

(gthr <- spr %>%
    gather(2:3, key = year, value = return))

# The types are not preserved. However, using the convert argument, can request for tydyr to try and find appropriate type

(stocks %>%
    spread(key = year, value = return, convert = TRUE) %>%
    gather(2:3, key = year, value = return, convert = TRUE))

# 2, need to use back-ticks or positional arguments
table4a %>%
  gather(`1999`, `2000`, key = "year", value = "cases")

```

# 12.3.3 Exercises (cont. 1)
```{r}
# 3
(people <- tribble(
  ~name,             ~key,    ~value,
  #-----------------|--------|------
  "Phillip Woods",   "age",       45,
  "Phillip Woods",   "height",   186,
  "Phillip Woods",   "age",       50,
  "Jessica Cordero", "age",       37,
  "Jessica Cordero", "height",   156
))

# Must add an extra column for repeat observations of the same individual
(people_fixed <- people %>%
    group_by(name, key) %>%
    mutate(
      obs = row_number()
    )
)

# Spreading should now work
(people_fixed %>%
    spread(key, value)
)
```

# 12.3.3 Exercises (cont. 2)
```{r}
# 4
(preg <- tribble(
  ~pregnant, ~male, ~female,
  "yes",     NA,    10,
  "no",      20,    12
  )
)

# Still doesn't really make sense
(preg <- preg %>%
    gather(male, female, key = "gender", value = "count"))

# might as well assume they're all female (assuming these are humans)
(preg <- preg %>%
    filter(gender == "female") %>%
    select(pregnant, count)
)
```

# 12.4 Separating and Uniting
```{r}
# Rate contains both cases & population in one column
table3

(table3 %>%
    separate(rate, into = c("cases", "population")))
# Explicitly specify a separating character, and try to convert data types
(table3 %>%
    separate(rate, into = c("cases", "population"), sep = "/", convert = TRUE))

# Try separating based on position
(table3 %>%
    separate(year, into = c("century", "year"), sep = 2))
```

# 12.3.2 Unite
```{r}
table5
(table5 %>%
    unite(year, century, year, sep="")
)
```

# 12.4.3 Exercises
```{r}
# 1
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"))

tibble(x = c("a,b,c", "d,e", "f,g,i")) %>% 
  separate(x, c("one", "two", "three"))

# 3
# Use a regex to split columns
(tibble(x = c("X_1", "X_2", "AA_1", "AA_2")) %>%
    extract(x, c("var", "id"), regex = "([A-Z])_([0-9])")
)
```

# 12.5 Missing Values
```{r}
# Explicitly vs. Implicitly missing
stocks <- tibble(
  year   = c(2015, 2015, 2015, 2015, 2016, 2016, 2016),
  qtr    = c(   1,    2,    3,    4,    2,    3,    4),
  return = c(1.88, 0.59, 0.35,   NA, 0.92, 0.17, 2.66)
)

# implicit -> explicit
(stocks %>%
    spread(year, return))
# or
(stocks %>%
    complete(year, qtr))

# explicit -> implicit
(stocks %>%
    spread(year, return) %>%
    gather(year, return, 2:3, na.rm = TRUE))

# Fill in "missing" values
(treatment <- tribble(
  ~ person,           ~ treatment, ~response,
  "Derrick Whitmore", 1,           7,
  NA,                 2,           10,
  NA,                 3,           9,
  "Katherine Burke",  1,           4
))

(treatment %>%
    fill(person))
(treatment %>%
    fill(person, .direction = "up"))

```

# 12.6 Case Study
```{r}
who

# Clean up using a bunch of intermediary dataframes
(who1 <- who %>%
    gather(5:60, key = "key", value = "cases", na.rm = TRUE)
)
(who1 %>%
    count(key))

# make the variable names consistent
(who2 <- who1 %>%
    mutate(key = stringr::str_replace(key, "newrel", "new_rel"))
)
# separate out the values for each 'code'
(who3 <- who2 %>%
    separate(key, c("new", "type", "sexage"), sep = "_")
)
# Drop redundant columns
(who4 <- who3 %>%
    select(-iso2, -iso3, -new)
)

# separate 'sexage' into 2 separate columns
# (who5 <- who4 %>%
#     separate(sexage, c("sex", "age"), sep=1))

(who5 <- who4 %>%
    extract(sexage, c("sex", "age"), regex = "([a-z]+)([0-9]+)") %>%
    # arranging by country makes it more intuitive to read chunks as a whole
    arrange(country)
)

# Do it all at once using pipes
(who_tidy <- who %>%
    gather(5:60, key = "key", value = "cases", na.rm = TRUE) %>%
    mutate(key = stringr::str_replace(key, "newrel", "new_rel")) %>%
    separate(key, c("new", "type", "sexage"), sep = "_") %>%
    select(-iso2, -iso3, -new) %>%
    extract(sexage, c("sex", "age"), regex = "([a-z]+)([0-9]+)") %>%
    arrange(country)
)
```

# 12.6.1 Exercises
```{r}
# 3
# iso2 and iso3 provide no additional information
(who3 %>%
   select(country, iso2, iso3) %>%
   distinct() %>%
   group_by(country) %>%
   filter(n() > 1)
)

# 4
# by country
(who_tidy %>%
    group_by(country) %>%
    summarize(total = sum(cases))
)
# How to visualize?

# by year
(who_tidy %>%
    group_by(year) %>%
    summarize(total = sum(cases)) %>%
    ggplot(aes(x = year, y = total)) +
      geom_line()
)

# by gender
(who_tidy %>%
    ggplot(aes(x = factor(1), fill = sex)) +
      geom_bar(width = 1) +
      coord_polar(theta = "y")
)
```

