---
title: "Chapter 13"
output: html_notebook
---

# 13.1.1
```{r}
library(tidyverse)
library(nycflights13)
library(viridis)
```

# 13.2 nycflights13
```{r}
flights
airlines
airports
planes
weather

# Verify that primary keys uniquely identify observations
planes %>%
  count(tailnum) %>%
  filter(n > 1)

weather %>%
  count(year, month, day, hour, origin) %>%
  filter(n > 1)

(flights %>%
    count(year, month, day, flight) %>%
    filter(n > 1)
)

(flights %>%
    count(year, month, day, tailnum) %>%
    filter(n > 1)
)
```

# 13.3.1 Exercises
```{r}
# 1
(flights %>%
   arrange(year, month, day, sched_dep_time, carrier, flight) %>%
   mutate(flight_id = row_number()) %>%
   select(flight_id, everything())
)
```

# 13.3.1 Exercises (cont. 1)
```{r}
# 2
(Lahman::Batting)
(Lahman::Batting %>%
    count(playerID, yearID, stint) %>%
    filter(n > 1)
)

(babynames::babynames)
(babynames::babynames %>%
    count(year, sex, name) %>%
    filter(nn > 1)
)

(nasaweather::atmos)
(nasaweather::atmos %>%
    count(lat, long, year, month) %>%
    filter(n > 1))

(fueleconomy::vehicles)
(fueleconomy::vehicles %>%
    count(id) %>%
    filter(n > 1))

# Can't seem to find one
(diamonds)
(diamonds %>%
    count(table) %>%
    filter(n > 1))
(diamonds %>%
    distinct() %>%
    nrow()
) / nrow(diamonds)

# num distinct rows < num rows (pigeonhole principle)
```

# 13.4 Mutating Joins
```{r}
flights2 <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2

# Combine airlines and flights2 data frames
flights2 %>%
  select(-origin, -dest) %>%
  left_join(airlines, by = "carrier")

# Can also do this using R's subsetting, but it's more cumbersome
(flights2 %>%
    select(-origin, -dest) %>%
    mutate(name = airlines$name[match(carrier, airlines$carrier)])
)
```

# 13.4.1 Unserstanding joins
```{r}
(x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
))
(y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
))
```

# 13.4.2 Inner join
```{r}
(x %>%
   inner_join(y, by = "key"))
```

# 13.4.3 Outer join
```{r}
(x %>%
   left_join(y, by = "key"))
(x %>%
    right_join(y, by = "key"))
(x %>%
    full_join(y, by = "key"))
```

# 13.4.4 Duplicate keys
```{r}
# Cases
# 1: one table has duplicate keys

x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     1, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2"
)
left_join(x, y, by = "key")

# 2: both tables have duplicate keys (usually an error)
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     3, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     2, "y3",
     3, "y4"
)
left_join(x, y, by = "key")
```

# 13.4.5 Defining the key columns
```{r}
# Use ALL variables that appear in both tables ('natural' join)
flights2 %>%
  left_join(weather)

# Use a character vector to select common variables
flights2 %>%
  left_join(planes, by = c("tailnum"))

# Combine flights data with airports data, where flights$dest and airports$faa are equivalent
flights2 %>%
  left_join(airports, c("dest" = "faa"))
# or origin and faa
flights2 %>%
  left_join(airports, c("origin" = "faa"))
```
```{r}
planes
```

# 13.4.6 Exercises
```{r}
# 1
(flights %>%
   # Find average delay by dest
   group_by(dest) %>%
   summarize(mean_arr_delay = mean(arr_delay, na.rm = TRUE)) %>%
   # join on the airports data frame
   left_join(airports, c("dest" = "faa")) %>%
   # Create map
   ggplot(aes(lon, lat, color = mean_arr_delay)) +
    borders("state") +
    geom_point() +
    coord_quickmap()
 )

# 2
(airport_locs <- airports %>%
    select(faa, lat, lon))

(flights2 %>%
    left_join(airport_locs, c("origin" = "faa"))) %>%
    left_join(airport_locs, c("dest" = "faa"))
```

# 13.4.6 Exercises (cont. 1)
```{r}
# 3
(plane_cohorts <- inner_join(flights,
                             select(planes, tailnum, plane_year = year),
                             by = "tailnum") %>%
   mutate(age = year - plane_year) %>%
   filter(!is.na(age)) %>%
   group_by(age) %>%
   summarize(
     dep_delay_mean = mean(dep_delay, na.rm = TRUE),
     dep_delay_sd = sd(dep_delay, na.rm = TRUE),
     arr_delay_mean = mean(arr_delay, na.rm = TRUE),
     arr_delay_sd = sd(arr_delay, na.rm = TRUE),
     n = n()
   )
)

ggplot(plane_cohorts, aes(x = age, y = dep_delay_mean)) +
  geom_ribbon(aes(ymin = dep_delay_mean - 2 * dep_delay_sd / sqrt(n),
                  ymax = dep_delay_mean + 2 * dep_delay_sd / sqrt(n)),
              alpha = 0.3) +
  geom_point()

ggplot(plane_cohorts, aes(x = age, y = arr_delay_mean)) +
  geom_ribbon(aes(ymin = arr_delay_mean - 2 * dep_delay_sd / sqrt(n),
                  ymax = arr_delay_mean + 2 * dep_delay_sd / sqrt(n)),
              alpha = 0.3) +
  geom_point()
```

# 13.4.6 Exercises (cont. 2)
```{r}
# 4
(flights_weather <- flights %>%
  inner_join(weather, by = c(
    "origin" = "origin",
    "year" = "year",
    "month" = "month",
    "day" = "day",
    "hour" = "hour"
  ))
)

(flights_weather %>%
    group_by(precip) %>%
    summarize(mean_dep_delay = mean(dep_delay, na.rm = TRUE)) %>%
    ggplot(aes(x = precip, y = mean_dep_delay)) +
      geom_point() +
      geom_smooth(method = "lm")
)

(flights_weather %>%
    group_by(wind_speed) %>%
    summarize(mean_dep_delay = mean(dep_delay, na.rm = TRUE)) %>%
    ggplot(aes(x = wind_speed, y = mean_dep_delay)) +
      geom_point() +
      geom_smooth(method = "lm"))
```


# 13.4.6 Exercises (cont. 3)
```{r}
(flights %>%
   filter(year == 2013, month == 6, day == 13) %>%
   group_by(dest) %>%
   summarize(mean_arr_delay = mean(arr_delay, na.rm = TRUE)) %>%
   inner_join(airports, by = c("dest" = "faa")) %>%
   ggplot(aes(y = lat, x = lon, color = mean_arr_delay, size = mean_arr_delay)) +
    borders("state") +
    geom_point() +
    coord_quickmap() +
    scale_color_viridis_c()
)
```

# 13.5 Filtering joins
```{r}
(top_dest <- flights %>%
   count(dest, sort = TRUE) %>%
   head(10)
)

# Find each flight that went to one of those destinations
(flights %>%
    filter(dest %in% top_dest[["dest"]])
)

# Semi-join
(flights %>%
    semi_join(top_dest))

# Anti-join
(flights %>%
    anti_join(planes, by = "tailnum") %>%
    count(tailnum, sort = TRUE)
)
```

# 13.5.1 Exercises
```{r}
```


