---
title: "Chapter 3"
output: html_notebook
---



```{r}
library(tidyverse)
```

```{r}
ggp_mpg <- ggplot2::mpg
ggp_mpg
```

# Create a GG Plot
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

# Graphing Template
```{r}
# ggplot(data = <DATA>) +
#   <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

# Exercises
```{r}
ggplot(data = ggp_mpg)
dim(ggp_mpg)
# f = front-wheel drive, r = rear wheel drive, 4 = 4wd
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = drv, y = class))
```

# Aesthetic Mappings
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

# Note: shouldn't use size for a discrete variable
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

# Exercises
```{r}
# 1
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = cty))

# 2
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = cty))

# 3
# You can't do this
# ggplot(data = ggp_mpg) +
#   geom_point(mapping = aes(x = displ, y = hwy, shape = cty))

# 4
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = cty, color = cty))

# 5
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class, stroke = .5))

# 6
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = displ < 5))

```

# Facets
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

# Exercises
```{r}
# 1
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cty)
# 2
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = drv, y = cyl))

# 3
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)

# 4
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)
```

# Geometric Objects
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

# Create overlay
ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv)) +
  geom_point(mapping = aes(x = displ, y = hwy, color=drv))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))

ggplot(data = ggp_mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

# cleaner
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()

# with different aesthetics for each plot
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()

# Specify different data for each layer
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)


```

# Exercises
```{r}
# 2
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  geom_smooth(se = FALSE)

# 6
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(mapping = aes(group = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(mapping = aes(group = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(mapping = aes(group = drv, color = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(mapping = aes(linetype = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(fill = drv), shape = 21, color = "white")
```

# Statistical Transformations
```{r}
# Using geom_bar()
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))

# Using stat()
ggplot(data = diamonds) +
  stat_count(mapping = aes(x = cut))

demo <- tribble(
  ~cut,        ~freq,
  "Fair",      1610,
  "Good",      4906,
  "Very Good", 12082,
  "Premium",   13791,
  "Ideal",     21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

# Using proportion
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

# Exercises
```{r}
ggplot(data = diamonds) +
  geom_pointrange(
    mapping = aes(x = cut, y = depth),
    stat = "summary",
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop..))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop.., group = color))

```

# Position Adjustments
```{r}
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, color = cut))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = cut))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity))

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) +
  geom_bar(alpha = 1/5, position = "identity")

ggplot(data = diamonds, mapping = aes(x = cut, color = clarity)) +
  geom_bar(fill = NA, position = "identity")

# Compare proportions across groups
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

# Place overlapping objects directly beside one another
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

# Jitter helps avoid overplotting -- only really useful for scatterplots
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")

# Vs without
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

# Shorthand for jitter
ggplot(data = mpg) +
  geom_jitter(mapping = aes(x = displ, y = hwy))
```

# Exercises
```{r}
# 1 -> fix by including some jitter
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point()

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_jitter()

# 3
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_count()

# 4
ggplot(data = mpg, aes(x = drv, y = hwy, color = class)) +
  geom_boxplot()
```

# Coordinate Systems
```{r}
# Avoid overlapping class labels
# vertical
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot()
# vs horizontal
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()

nz <- map_data("nz")

# Adjust aspect ratios
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()

bar <- ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = cut),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)
bar
bar + coord_flip()
bar + coord_polar()
```

# Exercises
```{r}
# 1
# stacked bar chart with single category
fig1 <- ggplot(data = mpg, aes(x = factor(1), fill = drv))
fig1 + geom_bar()
# pie chart version
fig1 + geom_bar(width = 1) + coord_polar(theta = "y")
# Bulls-eye chart
fig1 + geom_bar(width = 1) + coord_polar()

# Stacked bar chart with multiple categories
fig2 <- ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity))
fig2 + geom_bar(position = "fill")
fig2 + geom_bar(position = "fill") + coord_polar(theta = "y")

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity)) +
  coord_polar()

# 2
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip() +
  labs(y = "Highway MPG", x = "", title = "Highway MPG by car class")
```

