---
title: "Notebook 1 (Chapter 3)"
output: html_notebook
---



```{r}
library(tidyverse)
```

```{r}
ggp_mpg <- ggplot2::mpg
ggp_mpg
```

# Create a GG Plot
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

# Graphing Template
```{r}
# ggplot(data = <DATA>) +
#   <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

# Exercises
```{r}
ggplot(data = ggp_mpg)
dim(ggp_mpg)
# f = front-wheel drive, r = rear wheel drive, 4 = 4wd
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = drv, y = class))
```

# Aesthetic Mappings
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

# Note: shouldn't use size for a discrete variable
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

# Exercises
```{r}
# 1
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = cty))

# 2
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = cty))

# 3
# You can't do this
# ggplot(data = ggp_mpg) +
#   geom_point(mapping = aes(x = displ, y = hwy, shape = cty))

# 4
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = cty, color = cty))

# 5
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class, stroke = .5))

# 6
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = displ < 5))

```

# Facets
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

# Exercises
```{r}
# 1
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cty)
# 2
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = drv, y = cyl))

# 3
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)

# 4
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)
```

# Geometric Objects
```{r}
ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

# Create overlay
ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv)) +
  geom_point(mapping = aes(x = displ, y = hwy, color=drv))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

ggplot(data = ggp_mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))

ggplot(data = ggp_mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

ggplot(data = ggp_mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

# cleaner
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()

# with different aesthetics for each plot
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()

# Specify different data for each layer
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)


```

# Exercises
```{r}
# 2
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  geom_smooth(se = FALSE)

# 6
ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(mapping = aes(group = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(mapping = aes(group = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(mapping = aes(group = drv, color = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = drv)) +
  geom_smooth(mapping = aes(linetype = drv), se = FALSE)

ggplot(data = ggp_mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(fill = drv), shape = 21, color = "white")
```

# Statistical Transformations
```{r}
# Using geom_bar()
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))

# Using stat()
ggplot(data = diamonds) +
  stat_count(mapping = aes(x = cut))

demo <- tribble(
  ~cut,        ~freq,
  "Fair",      1610,
  "Good",      4906,
  "Very Good", 12082,
  "Premium",   13791,
  "Ideal",     21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

# Using proportion
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

# Exercises
```{r}
ggplot(data = diamonds) +
  geom_pointrange(
    mapping = aes(x = cut, y = depth),
    stat = "summary",
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop..))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))
```

```{r}
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop.., group = color))
```

